#AI and Data Science Workshop with Python
Introduction to Numpy


Assignment 01


1- Create a NumPy array and test whether any elements of the array are non-zero
a sample output can be like this:
```
[1 2 3 4]
True
[0 1 2 3]
False
```

2- Create a NumPy array of integer in range of 30 to 70
the result can be as follow:
```
Array of the integers from 30 to70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]
 ```


3- Create two NumPy array with the same number of elements and compare them to see if their elements are equal. you can use `equal()` function

A sample result can be as follow:
Original numbers:
```
[ 12  43  56  14  67  -1 120 -12  60  10]
[ 12.        43.        56.        14.        67.        -1.
 120.       -12.        60.        10.000001]
Comparison - equal:
[ True  True  True  True  True  True  True  True  True False]
```

4- Write a NumPy program to create a 3X4 array and iterate over it to print the items

5- Using NumPy, create a 4x5 matrix filled with values from 1 to 20

6- We have created a matrix of size 5x4 as follow:

In [ ]:
import numpy as np
sizes = np.array(
[[2,  8, 8, 3],
[6,  13, 1, 6],
[9,  5, 3, 7],
[3,  22, 9, 2],
[12, 7, 2, 9]])

Write a NumPy code that retrieves the last column of sizes matrix:

Write a Numpy code that retrieves the following submatrix from `sizes`:

```
array([[13,  1],
       [ 5,  3]])
```

Write a NumPy program that in result create an array containing such items of the sizes matrix, which are greater than 10