## Drive Mounting

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## Data Types

In [ ]:
# Integers
num1 = 10
num2 = 100
print(num1 + num2)

110


In [ ]:
# Float Numbers
a = 10.5
b = 8.9
print(a - b)

1.5999999999999996


In [ ]:
# Complex Numbers
x = 3 + 4j
y = 9 + 8j
print(y - x)

(6+4j)


In [ ]:
# Finding the Data Type of a Number

# int
num1 = 100
print("Type of num1: ", type(num1))

# float
num2 = 10.99
print("Type of num2: ", type(num2))

# complex numbers
num3 = 3 + 4j
print("Type of num3: ", type(num3))

Type of num1:  <class 'int'>
Type of num2:  <class 'float'>
Type of num3:  <class 'complex'>


In [ ]:
# Checks whether a number belongs to a particular data type and returns true or false based on the result.

num = 100
# true because num is an integer
print(isinstance(num, int))

# false because num is not a float
print(isinstance(num, float))

# false because num is not a complex number
print(isinstance(num, complex))

True
False
False


## Variables

In [ ]:
# Assignment
num = 100
string = "Gonzalez"
print(num)
print(string)

100
Gonzalez


In [ ]:
# Multiple Assignment
x = y = z = 99
print(x)
print(y)
print(z)

In [ ]:
# Multiple Assignment
a, b, c = 5, 6, 7
print(a)
print(b)
print(c)

In [ ]:
# Swaping
x, y = 6, 3
x, y = y, x
print(x)
print(y)

In [ ]:
# Accessing Non-Existent Name
x = 10
y = x + unnamedVariable

NameError: ignored

## Input/Output

In [ ]:
# Input
num1 = int(input("Enter number 1: "))
num2 = int(input("Enter number 2: "))

# Process Input
mult = num1 * num2
div = num1 / num2

# Output
print(num1, "*", num2, "is", mult)
print("%d / %d is %d" % (num1, num2, div))

Enter number 1: 10
Enter number 2: 5
10 * 5 is 50
10 / 5 is 2


## Arithmetic Operations

In [ ]:
# Precedence 
num1 = 10 ** 2 + 1 / 5
num2 = 10 ** (2 + 1) / 5
num3 = 10 ** (2 + 1 / 5)
num4 = 10 ** (2 + 1 // 5)
print(num1)
print(num2)
print(num3)
print(num4)

100.2
200.0
158.48931924611142
100


## Flow Control: Conditional Statements

####   if Statement


In [ ]:
# Example
value = False
if value:
   print("Got a true expression value ",value)
else:
   print("Got a false expression value ",value)

Got a false expression value  False


In [ ]:
# Validating the value of a variable
flag = True
if flag == True:
    print("Welcome")
    print("To")
    print("ITESM 2020 Training")

Welcome
To
ITESM 2020 Training


In [ ]:
# We can obtain the same result using:
flag = True
if flag:
    print("Welcome")
    print("To")
    print("ITESM 2020 Training")



Welcome
To
ITESM 2020 Training


In [ ]:
# Validating if the variable is false
flag = False
if flag:
    print("You Guys")
    print("are")
    print("Awesome")

In [ ]:
# Example with numerical Values
num = 100
if num < 200:
    print("num is less than 200")

num is less than 200


#### if-else Statement

In [ ]:
# Example:
num = 22
if num % 2 == 0:
    print("Even Number")
else:
    print("Odd Number")

Even Number


#### if-elif-else statement

In [ ]:
# Example:
num = 1122
if 9 < num < 99:
    print("Two digit number")
elif 99 < num < 999:
    print("Three digit number")
elif 999 < num < 9999:
    print("Four digit number")
else:
    print("number is <= 9 or >= 9999")

Four digit number


In [ ]:
# Example:
value = 101
if value == 200:
   print("value is 200")
elif value == 150:
   print("value is 150")
elif value == 100:
   print("value is 100")
else:
   print("value is not (100,150,200)")
print("End!")

value is not (100,150,200)
End!


## Control Flow: Loops

#### for loops

In [ ]:
# Example:
fruits = ['banana', 'apple',  'mango']
for fruit in fruits:        
   print(fruit)

banana
apple
mango


In [ ]:
# Example:
fruits = ['banana', 'apple',  'mango']
for index in range(len(fruits)):
   print(fruits[index])

banana
apple
mango


In [ ]:
# Program to print squares of all numbers present in a list

# List of integer numbers
numbers = [1, 2, 4, 6, 11, 20]

# variable to store the square of each num temporary
sq = 0

# iterating over the given list
for val in numbers:
    # calculating square of each number
    sq = val * val
    # displaying the squares
    print(sq)

1
4
16
36
121
400


In [ ]:
# Using the range function in a for loop:

# Program to print the sum of first 5 natural numbers

# variable to store the sum
sum = 0

# iterating over natural numbers using range()
for val in range(1, 6):
    # calculating sum
    sum = sum + val

# displaying sum of first 5 natural numbers
print(sum)

15


In [ ]:
# For loop with else block

# The else block will only execute once the loop block has completed
for val in range(5):
	print(val)
else:
	print("The loop has completed execution")

0
1
2
3
4
The loop has completed execution


In [ ]:
# Nested for loop: A loop within a loop
for num1 in range(3):
	for num2 in range(10, 14):
		print(num1, ",", num2)

0 , 10
0 , 11
0 , 12
0 , 13
1 , 10
1 , 11
1 , 12
1 , 13
2 , 10
2 , 11
2 , 12
2 , 13


#### while loops

In [ ]:
# Example:

count = 0
while (count < 9):
   print("The count is:", count)
   count = count + 1

The count is: 0
The count is: 1
The count is: 2
The count is: 3
The count is: 4
The count is: 5
The count is: 6
The count is: 7
The count is: 8


In [ ]:
# Example:
num = 1

# loop will repeat itself as long as num < 10 remains true
while num < 10:
    print(num)
    #incrementing the value of num
    num = num + 3

1
4
7


In [ ]:
# Common Error - Infinite while loop
while True:
   print("hello")

In [ ]:
# Common Error - Infinite while loop
num = 1
while num < 5:
   print(num)

In [ ]:
# Nested while loop - A while loop within a while loop
i = 1
j = 5
while i < 4:
    while j < 8:
        print(i, ",", j)
        j = j + 1
        i = i + 1

1 , 5
2 , 6
3 , 7


In [ ]:
# While loop with else block

# We can have a ‘else’ block associated with while loop. The ‘else’ block is optional. It executes only after the loop finished execution.
num = 10
while num > 6:
   print(num)
   num = num - 1
else:
   print("loop is finished")

10
9
8
7
loop is finished


#### break, continue, and pass statements

In [ ]:
# break

# In this example, we are searching a number ’88’ in the given list of numbers. 
# The requirement is to display all the numbers till the number ’88’ is found and when it is found, 
# terminate the loop and do not display the rest of the numbers.

# program to display all the elements before number 88
for num in [11, 9, 88, 10, 90, 3, 19]:
   print(num)
   if(num == 88):
	   print("The number 88 is found")
	   print("Terminating the loop")
	   break

11
9
88
The number 88 is found
Terminating the loop


In [ ]:
# continue

# program to display only odd numbers
for num in [20, 11, 9, 66, 4, 89, 44]:
    # Skipping the iteration when number is even
    if num % 2 == 0:
        continue
    # This statement will be skipped for all even numbers
    print(num)

11
9
89


In [ ]:
# pass

for num in [20, 11, 9, 66, 4, 89, 44]:
    if num % 2 == 0:
        pass
    else:
        print(num)

11
9
89


## List

In [ ]:
# Creating a List

# To create a list all you have to do is to place the items inside a square bracket [] separated by comma ,.

# list of floats
num_list = [11.22, 9.9, 78.34, 12.0]

# list of int, float and strings
mix_list = [1.13, 2, 5, 'itesm', 100, 'hi']

# an empty list
nodata_list = []

# Printing a List
print(num_list)
print(mix_list)
print(nodata_list)

[11.22, 9.9, 78.34, 12.0]
[1.13, 2, 5, 'itesm', 100, 'hi']
[]


In [ ]:
# Check the number of elements for each list
print(len(num_list))
print(len(mix_list))
print(len(nodata_list))

4
6
0


In [ ]:
# Accesing the items of a list

# a list of numbers
numbers = [11, 22, 33, 100, 200, 300]

# prints 11
print(numbers[0])

# prints 300
print(numbers[5])

# prints 22
print(numbers[1])

11
300
22


In [ ]:
# Common Errors - Using a float number to access an Index

# a list of numbers
numbers = [11, 22, 33, 100, 200, 300]

# error
print(numbers[1.0])

TypeError: ignored

In [ ]:
# Common Errors - Accessing an index out of range

# a list of numbers
numbers = [11, 22, 33, 100, 200, 300]

# error
print(numbers[6])

IndexError: ignored

In [ ]:
# Negative Index to access the list items from the end

# a list of strings
my_list = ['hello', 'world', 'hi', 'bye']

# prints "bye"
print(my_list[-1])

# prints "world"
print(my_list[-3])

# prints "hello"
print(my_list[-4])

bye
world
hello


In [ ]:
# Getting a sublist in Python using slicing

# list of numbers
n_list = [1, 2, 3, 4, 5, 6, 7]

# list items from 2nd to 3rd
print(n_list[1: 3])

# list items from beginning to 3rd
print(n_list[: 3])

# list items from 4th to end of list
print(n_list[3 :])

# Whole list
print(n_list[:])

[2, 3]
[1, 2, 3]
[4, 5, 6, 7]
[1, 2, 3, 4, 5, 6, 7]


In [ ]:
# List Operations - Adding new elements to List

# list of numbers
n_list = [1, 2, 3, 4]

# 1. adding item at the desired location
# adding element 100 at the fourth location
n_list.insert(3, 100)

# list: [1, 2, 3, 100, 4]
print(n_list)

# 2. adding element at the end of the list
n_list.append(99)

# list: [1, 2, 3, 100, 4, 99]
print(n_list)

# 3. adding several elements at the end of list
# the following statement can also be written like this:
# n_list + [11, 22]
n_list.extend([11, 22])

# list: [1, 2, 3, 100, 4, 99, 11, 22]
print(n_list)

[1, 2, 3, 100, 4]
[1, 2, 3, 100, 4, 99]
[1, 2, 3, 100, 4, 99, 11, 22]


In [ ]:
# List Operations - Updating elements in a list

# list of numbers
n_list = [1, 2, 3, 4]

# Changing the value of 3rd item
n_list[2] = 100

# list: [1, 2, 100, 4]
print(n_list)

# Changing the values of 2nd to fourth items
n_list[1 : 4] = [11, 22, 33]

# list: [1, 11, 22, 33]
print(n_list)

[1, 2, 100, 4]
[1, 11, 22, 33]


In [ ]:
# List Operations - Deleting elements in a list

# list of numbers
n_list = [1, 2, 3, 4, 5, 6]

# Deleting 2nd element
del n_list[1]

# list: [1, 3, 4, 5, 6]
print(n_list)

# Deleting elements from 3rd to 4th
del n_list[2 : 4]

# list: [1, 3, 6]
print(n_list)

# Deleting the whole list
del n_list

[1, 3, 4, 5, 6]
[1, 3, 6]


In [ ]:
# List Operations - Deleting elements using remove(), pop() and clear() methods
# remove(item): Removes specified item from list.
# pop(index): Removes the element from the given index.
# pop(): Removes the last element.
# clear(): Removes all the elements from the list.

# list of chars
ch_list = ['A', 'F', 'B', 'Z', 'O', 'L']

# Deleting the element with value 'B'
ch_list.remove('B')

# list: ['A', 'F', 'Z', 'O', 'L']
print(ch_list)

# Deleting 2nd element
ch_list.pop(1)

# list: ['A', 'Z', 'O', 'L']
print(ch_list)

# Deleting all the elements
ch_list.clear()

# list: []
print(ch_list)

['A', 'F', 'Z', 'O', 'L']
['A', 'Z', 'O', 'L']
[]


In [ ]:
# Other Operations
some_list = ['physics', 'math', 1997, 2000];
print (len(some_list))
some_list = some_list + ['AI', 2018]
print(some_list)
print(some_list * 2)

4
['physics', 'math', 1997, 2000, 'AI', 2018]
['physics', 'math', 1997, 2000, 'AI', 2018, 'physics', 'math', 1997, 2000, 'AI', 2018]


## Tuple

In [ ]:
# Creating Tuples
tup1 = ('physics', 'chemistry', 1997, 2000)
tup2 = (1, 2, 3, 4, 5 )
tup3 = 'a', 'b', 'c', 'd'
print(type(tup3))

# Accessing Values
print(len(tup1))
tup2 = (1, 2, 3, 4, 5, 6, 7 )
print("tup1[0]: ", tup1[0])
print("tup2[1 : 5]: ", tup2[1 : 5])

<class 'tuple'>
4
tup1[0]:  physics
tup2[1 : 5]:  (2, 3, 4, 5)


In [ ]:
# Common Errors - Modifying a value
tup1[0] = 100

TypeError: ignored

## String

In [ ]:
# Creating a String

# lets see the ways to create strings in Python
str = 'itesm2020'
print(str)

str2 = "Chaitanya"
print(str2)

# multi-line string
str3 = """Welcome to 
   itesm 2020 training"""
print(str3)

str4 = '''This is a tech 
   blog'''
print(str4)

itesm2020
Chaitanya
Welcome to 
   itesm 2020 training
This is a tech 
   blog


In [ ]:
# Accessing elements in a string
str = "Kevin"

# displaying whole string
print(str)

# displaying first character of string
print(str[0])

# displaying third character of string
print(str[2])

# displaying the last character of the string
print(str[-1])

# displaying the second last char of string
print(str[-2])

Kevin
K
v
n
i


In [ ]:
# String Operations - Slicing operation
str = "Star Wars is Amazing"

# displaying whole string
print("The original string is: ", str)

# slicing 10th to the last character
print("str[9 :]: ", str[9 :])

# slicing 3rd to 6th character
print("str[2 : 6]: ", str[2 : 6])

# slicing from start to the 9th character
print("str[: 9]: ", str[: 9])

# slicing from 10th to second last character
print("str[9 : -1]: ", str[9 : -1])

The original string is:  Star Wars is Amazing
str[9:]:   is Amazing
str[2:6]:  ar W
str[:9]:  Star Wars
str[9:-1]:   is Amazin


In [ ]:
# String Operations - Concatenation
str1 = "One"
str2 = "Two"
str3 = "Three"

# Concatenation of three strings
print(str1 + str2 + str3)

OneTwoThree


In [ ]:
# String Operations - Repeating a String
str = "ABC"

# repeating the string str by 3 times
print(str * 3)

ABCABCABC


In [ ]:
# String Operations - Membership Opertions
str = "Welcome to itesm 2020 training"
str2 = "Welcome"
str3 = "Chaitanya"
str4 = "XYZ"

# str2 is in str? True
print(str2 in str)

# str3 is in str? False
print(str3 in str)

# str4 not in str? True
print(str4 not in str)

True
False
True


In [ ]:
# String Operations - Relational Operators on Strings
# The relational operators works on strings based on the ASCII values of characters.

# The ASCII value of a is 97, b is 98 and so on.
# The ASCII value of A is 65, B is 66 and so on.

str = "ABC"
str2 = "aBC"
str3 = "XYZ"
str4 = "XYz"

# ASCII value of str2 is > str? True
print(str2 > str)

# ASCII value of str3 is > str4? False
print(str3 > str4)

True
False


In [ ]:
# Convert String to List and List to String
string = "Geeks for Geeks"
      
# Splitting a string into list
list_string = string.split(' ')
print(list_string)
  
# Join list of strings into one
new_string = '-'.join(list_string)
print(new_string)

['Geeks', 'for', 'Geeks']
Geeks-for-Geeks


## Dictionaries

In [ ]:
# Creating a dictionary
mydict = {'StuName': 'Ajeet', 'StuAge': 30, 'StuCity': 'Agra'}

print("Student Age is:", mydict['StuAge'])
print("Student City is:", mydict['StuCity'])

Student Age is: 30
Student City is: Agra


In [ ]:
# Common Errors - Looking for non-existing keys
print("Student Age is:", mydict['StuClass'])

KeyError: ignored

In [ ]:
# Changing values in a Dictionary
mydict = {'StuName': 'Ajeet', 'StuAge': 30, 'StuCity': 'Agra'}
print("Student Age before update is:", mydict['StuAge'])
print("Student City before update is:", mydict['StuCity'])

mydict['StuAge'] = 31
mydict['StuCity'] = 'Noida'
print("Student Age after update is:", mydict['StuAge'])
print("Student City after update is:", mydict['StuCity'])

Student Age before update is: 30
Student City before update is: Agra
Student Age after update is: 31
Student City after update is: Noida


In [ ]:
# Adding new key-pair values
mydict = {'StuName': 'Steve', 'StuAge': 4, 'StuCity': 'Agra'}
mydict['StuClass'] = 'Jr.KG'
print("Student Name is:", mydict['StuName'])
print("Student Class is:", mydict['StuClass'])

Student Name is: Steve
Student Class is: Jr.KG


In [ ]:
# Looping through a dictionary
mydict = {'StuName': 'Steve', 'StuAge': 4, 'StuCity': 'Agra'}
for e in mydict:
  print("Key:",e,"Value:",mydict[e])

Key: StuName Value: Steve
Key: StuAge Value: 4
Key: StuCity Value: Agra


In [ ]:
# Updation dictionaries
dict = {'Name': 'Zara', 'Age': 7, 'Class': 'First'}
dict['Age'] = 8; # update existing entry
dict['School'] = "DPS School"; # Add new entry
print (dict)

{'Name': 'Zara', 'Age': 8, 'Class': 'First', 'School': 'DPS School'}


In [ ]:
# Useful functions
print(dict.keys())
print(dict.values())
dict.clear()
print(dict)

dict_keys(['Name', 'Age', 'Class', 'School'])
dict_values(['Zara', 8, 'First', 'DPS School'])
{}


In [ ]:
# Creating dictionaries from list
L1 = ['a','b','c','d']
L2 = [1,2,3,4]
d = dict(zip(L1,L2))
print(d)

{'a': 1, 'b': 2, 'c': 3, 'd': 4}


## Functions

In [ ]:
# Lets define a function for adding numbers:
def add(num1, num2):
    return num1 + num2

# Outside function
sum1 = add(100, 200)
sum2 = add(8, 9)
print(sum1)
print(sum2)

300
17


In [ ]:
# Using default arguments in a function:

# Now that we know how to declare and call a function, lets see how can we use the default arguments. 
# By using default arguments we can avoid the errors that may arise while calling a function without 
# passing all the parameters. 

# default argument for second parameter
def add(num1, num2=1):
    return num1 + num2

# Outside function
sum1 = add(100, 200)
sum2 = add(8)  # used default argument for second param
sum3 = add(100)  # used default argument for second param
print(sum1)
print(sum2)
print(sum3)

300
9
101


In [ ]:
# Defining function
def printinfo( student_dict ):
    print("Info of Student:")
    print("Name:", student_dict['name'])
    print("Class:", student_dict['class'])
    print("School:", student_dict['school'])
    print("Age:", student_dict['age'])
    return;

# Outside function
studentName = input("Enter name: ")
studentAge = input("Enter age: ")
studentClass = input("Enter class: ")
studentSchool = input("Enter school: ")

some_student = {'name': studentName, 'age': studentAge, 'class': studentClass, 'school': studentSchool}
printinfo(some_student)

Enter name: Zara
Enter age: 7
Enter class: First
Enter school: DPS School
Info of Student:
Name: Zara
Class: First
School: DPS School
Age: 7


In [ ]:
# Example of recursion in Python to
# find the factorial of a given number

def factorial(num):
    """This function calls itself to find
    the factorial of a number"""

    if num == 1:
        return 1
    else:
        return (num * factorial(num - 1))


num = 5
print("Factorial of", num, "is:", factorial(num))

Factorial of 5 is: 120


In [ ]:
# Lamba Example 1
print((lambda x: x + 1)(2)

3

In [ ]:
# Lambda Example 2
adder = lambda x, y: x + y
print (adder (1, 2))


3


## Modules: NumPy

#### Impoting and Creating a numPy

In [ ]:
# Import numPy
import numpy as np

# Create a list
my_list = [1, 2, 3, 4]
print("my_list:", my_list)

# Use that list to create a numPy array
np_array = np.array(my_list)
print("np_array:", np_array)
print("type of np_array:", type(np_array))

my_list: [1, 2, 3, 4]
np_array: [1 2 3 4]
type of np_array: <class 'numpy.ndarray'>


#### Built-in Methods of numPy 

arange: Return evenly spaced values within a given interval.

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

zeros and ones: Generate arrays of zeros or ones

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

linspace: Returns numbers evenly spaced samples, calculated over the interval

In [ ]:
np.linspace(0, 9, 10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
np.linspace(0, 5, 20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [ ]:
np.linspace(0, 5, 21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

eye: Creates an identity matrix

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

random.rand: Creates an array of the given shape and populates it with random samples from a uniform distribution over [0, 1)

In [ ]:
np.random.seed(7)
np.random.rand(2)

array([0.07630829, 0.77991879])

In [ ]:
np.random.rand(2)

array([0.43840923, 0.72346518])

In [ ]:
np.random.rand(5, 5)

array([[0.97798951, 0.53849587, 0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904, 0.38094113, 0.06593635],
       [0.2881456 , 0.90959353, 0.21338535, 0.45212396, 0.93120602],
       [0.02489923, 0.60054892, 0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258, 0.75040986, 0.66901324]])

randn: Returns a sample (or samples) from the "standard normal" distribution [σ = 1]. Unlike rand which is uniform, values closer to zero are more likely to appear.

In [ ]:
np.random.randn(2)

array([-1.43532596, -0.15681862])

In [ ]:
np.random.seed(7)
np.random.randn(5, 5)

array([[ 1.69052570e+00, -4.65937371e-01,  3.28201637e-02,
         4.07516283e-01, -7.88923029e-01],
       [ 2.06557291e-03, -8.90385858e-04, -1.75472431e+00,
         1.01765801e+00,  6.00498516e-01],
       [-6.25428974e-01, -1.71548261e-01,  5.05299374e-01,
        -2.61356415e-01, -2.42749079e-01],
       [-1.45324141e+00,  5.54580312e-01,  1.23880905e-01,
         2.74459924e-01, -1.52652453e+00],
       [ 1.65069969e+00,  1.54335535e-01, -3.87139943e-01,
         2.02907222e+00, -4.53860299e-02]])

randint

In [ ]:
np.random.randint(1, 100)

93

In [ ]:
np.random.randint(1, 100, 10)

array([72, 24, 11, 36, 65, 62,  8, 24, 93, 97])

seed

In [ ]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

#### Array Attributes and Other Methods

In [ ]:
np_array = np.arange(25)
np_random_array = np.random.randint(0, 50, 10)
print(np_array)
print(np_random_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[21  1 23 43 29 37  1 20 32 11]


Reshape: Returns an array containing the same data with a new shape.

In [ ]:
np_array.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

max, min, argmax, argmin: useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:
np_random_array

array([21,  1, 23, 43, 29, 37,  1, 20, 32, 11])

In [ ]:
np_random_array.max()

43

In [ ]:
np_random_array.argmax()

3

In [ ]:
np_random_array.min()

1

In [ ]:
np_random_array.argmin()

1

Shape: Is an attribute that arrays have (not a method)

In [ ]:
# Vector
np_array.shape

(25,)

In [ ]:
# Notice the two sets of brackets
np_array.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
np_array.reshape(1, 25).shape

(1, 25)

In [ ]:
np_array.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
np_array.reshape(25, 1).shape

(25, 1)

dtype: Grabs the data type of the object in the array

In [ ]:
np_array.dtype

dtype('int64')

In [ ]:
np_array = np.array([1.2, 3.4, 5.6])
np_array.dtype

dtype('float64')

## Handling Files

In [ ]:
# myfile.txt contains:
# I am learning Python programming.
# Python is an interesting language.

# Open file
myfile = open("/content/drive/MyDrive/Google Colab Files/myfile.txt", "r")

# Process file
for line in myfile:
  print(line, end = "")

# Close file
myfile.close()

I am learning Python programming.
Python is an interesting language.


In [ ]:
# StudentInfo.csv contains:
# ID,Name,Grade 
# 109,John,A 
# 289,Zara,B 
# 157,Richard,C 
# 322,Sophia,A 

myfile = open("/content/drive/MyDrive/Google Colab Files/StudentInfo.csv", "r")

# Discarding the first line and initialize list
myfile.readline()
mylist = []

# Reading file and storing each line in a list
for line in myfile:
  line = line[: len(line) - 1]  # Remove newline
  mylist.append(line)

print("After Reading:", mylist)

# Separating the values in each line in the list to access them
for index in range(len(mylist)):
  mylist[index] = mylist[index].split(",")

print("After Processing:", mylist)

After Reading: ['109,John,A', '289,Zara,B', '157,Richard,C', '322,Sophia,A']
After Processing: [['109', 'John', 'A'], ['289', 'Zara', 'B'], ['157', 'Richard', 'C'], ['322', 'Sophia', 'A']]


In [ ]:
# Printing students with grade A. Indexing: ID = 0, name = 1, and grades = 2
def printStudentInfo(studentInfo):
  print("ID:", studentInfo[0], end = ", ")
  print("Name:", studentInfo[1], end = ", ")
  print("Grade:", studentInfo[2])

for student in mylist:
  if student[2] == 'A':
    printStudentInfo(student)

ID: 109, Name: John, Grade: A
ID: 322, Name: Sophia, Grade: A


## Exception Handling

In [ ]:
# Example:
try:
   fh = open("testfile", "w")
   fh.write("This is my test file for exception handling!!")
except IOError:
   print("Error: can\'t find file or read data")
else:
   print("Written content in the file successfully")
   fh.close()

Written content in the file successfully


In [ ]:
# Example:
try:
   fh = open("testfile", "r")
   fh.write("This is my test file for exception handling!!")
except IOError:
   print("Error: can\'t find file or read data")
else:
   print("Written content in the file successfully")

Error: can't find file or read data
