In [ ]:
import numpy as np

Conditional Selection

In [ ]:
# make a numpy array
npArray = np.arange(1,11)
print("npArray:",npArray)

npArray: [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#are the 
npArray > 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
# store the array
boolArray = npArray > 4

In [ ]:
print(boolArray)

[False False False False  True  True  True  True  True  True]


In [ ]:
npArray[boolArray]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
npArray[npArray > 6]

array([ 7,  8,  9, 10])

In [ ]:
x = 2
npArray[npArray > x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

Numpy Arithmatic Operation

In [2]:
import numpy as np
npArray = np.arange(0,10)
print("npArray:",npArray)

npArray: [0 1 2 3 4 5 6 7 8 9]


In [3]:
npArray + npArray

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
npArray * npArray

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [5]:
npArray - npArray

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
npArray / npArray

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1 / npArray


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
npArray ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

Universal Array Functions

In [ ]:
np.sqrt(npArray)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.exp(npArray)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.sin(npArray)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(npArray)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])


Indexing a 2D array (matrices)

In [ ]:
npArray2d = np.array(([5,10,15],
                        [20,25,30],
                        [35,40,45]))


npArray2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
npArray2d[1]

array([20, 25, 30])

In [ ]:
npArray2d[1][0]

20

In [ ]:
npArray2d[1,0]

20

In [ ]:
npArray2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
npArray2d[2]

array([35, 40, 45])

In [ ]:
npArray2d[2,:]

array([35, 40, 45])